; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
	knolleary/PubSubClient@^2.8
	esp32async/ESPAsyncWebServer @ ^3.10.3
extra_scripts = pre:minify.py
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags = 
	-DCONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=1
	-DCONFIG_ESP_COREDUMP_ENABLE_TO_UART=1
	-DCONFIG_ESP_COREDUMP_DATA_FORMAT_ELF=1
	-DCONFIG_ESP_COREDUMP_CHECKSUM_CRC32=1
	-DCONFIG_ESP_TASK_WDT_PANIC=1
	-DCONFIG_ESP_COREDUMP_DECODE_INFO=1
monitor_speed = 115200
monitor_filters = 
	time
	esp32_exception_decoder
	log2file

[env:esp32devdbg]
build_type = debug
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
	knolleary/PubSubClient@^2.8
extra_scripts = pre:minify.py
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs

[env:esp32c3dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	lsatan/SmartRC-CC1101-Driver-Lib@^2.5.7
	knolleary/PubSubClient@^2.8
extra_scripts = pre:minify.py
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs
